# Generated by Django 5.2.6 on 2025-10-02 11:33

import djangocms_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_blog", "0049_alter_blogcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorentriesplugin",
            name="template_folder",
            field=models.CharField(
                choices=djangocms_blog.models.get_choices_template_folder,
                default=djangocms_blog.models.get_default_template_folder,
                help_text="Select plugin template to load for this instance",
                max_length=200,
                verbose_name="Plugin template",
            ),
        ),
        migrations.AlterField(
            model_name="genericblogplugin",
            name="template_folder",
            field=models.CharField(
                choices=djangocms_blog.models.get_choices_template_folder,
                default=djangocms_blog.models.get_default_template_folder,
                help_text="Select plugin template to load for this instance",
                max_length=200,
                verbose_name="Plugin template",
            ),
        ),
        migrations.AlterField(
            model_name="latestpostsplugin",
            name="template_folder",
            field=models.CharField(
                choices=djangocms_blog.models.get_choices_template_folder,
                default=djangocms_blog.models.get_default_template_folder,
                help_text="Select plugin template to load for this instance",
                max_length=200,
                verbose_name="Plugin template",
            ),
        ),
        migrations.AlterField(
            model_name="mostreadplugin",
            name="template_folder",
            field=models.CharField(
                choices=djangocms_blog.models.get_choices_template_folder,
                default=djangocms_blog.models.get_default_template_folder,
                help_text="Select plugin template to load for this instance",
                max_length=200,
                verbose_name="Plugin template",
            ),
        ),
    ]
